# Generated by Django 5.2.9 on 2025-12-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('designation', models.CharField(max_length=100)),
                ('role', models.CharField(default='librarian', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Librarian_Information',
                'ordering': ['email'],
            },
        ),
        migrations.AlterModelTable(
            name='book',
            table='Book_Details',
        ),
    ]
