# Generated by Django 5.2.9 on 2025-12-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0003_alter_register_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
