# Generated by Django 5.2.9 on 2026-01-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0007_alter_register_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='confirm_password',
            field=models.CharField(null=True),
        ),
    ]
